const pelamarAwalSchema = {
  type: "object",
  properties: {
    status: { type: "number" },
    message: { type: "string" },
    data: {
      type: "object",
      properties: {
        id: { type: "number" },
        userId: { type: "string" },
        email: { type: "string" },
        nik: { type: "string" },
        nomorID: { type: "string" },
        jenisIdentitas: { type: "string" },
        nama: { type: "string" },
        namaPanggilan: { type: "string" },
        profesionalTitle: { type: "string" },
        jenisKelamin: { type: "string" },
        alamat: { type: "string" },
        domisili: { type: "string" },
        alamatSesuaiIdentitas: { type: "string" },
        kelurahanSesuaiIdentitas: { type: "string" },
        nomorTelponTempatTinggal: { type: "string" },
        nomorHP: { type: "string" },
        tempatLahir: { type: "string" },
        tanggalLahir: { type: "string" },
        tanggalLamaran: { type: "string" },
        kodePelamar: { type: "string" },
        attachmentProfilePhotoId: { type: "number" },
        profilePhotoUri: { type: "string" },
        attachmentCVId: { type: "number" },
        attachmentIjazahId: { type: "number" },
        attachmentTranskripId: { type: "number" },
        cvUri: { type: "string" },
        ijazahUri: { type: "string" },
        transkripUri: { type: "string" },
        blackListed: { type: "boolean" },
        invitedBy: { type: "string" },
        lamaran: {
          type: "object",
          properties: {
            personId: { type: "number" },
            applyDate: { type: "string" },
            currentSalary: { type: "number" },
            expectedSalary: { type: "number" },
            onsite: { type: "boolean" },
            remote: { type: "boolean" },
            kesiapanJoin: { type: "string" },
            statusPekerjaanSekarang: { type: "string" },
            alasanKeluar: { type: "string" },
            concernLokasiKerja: { type: "string" },
            concernIndustry: { type: "string" },
            contractBaseOk: { type: "boolean" },
            selesaiKontrak: { type: "string" },
            namaReferensi: { type: "string" },
            nomorTelponReferensi: { type: "string" },
            statusRekomendasi: { type: "string" },
            gradeSalary: { type: "string" },
            softSkill: { type: "string" },
            notAvailable: { type: "boolean" },
            notAvailableNote: { type: "string" },
            hiringStatus: { type: "string" },
            sudahInterviewTro: { type: "boolean" },
            tro: { type: "string" },
            jadwalInterviewTro: { type: "string" },
            waktuInterviewTro: { type: "string" },
            sudahInterviewRo: { type: "boolean" },
            ro: { type: "string" },
            jadwalInterviewRo: { type: "string" },
            waktuInterviewRo: { type: "string" },
            source: { type: "string" },
            invitedBy: { type: "string" },
          },
        },
        jobRoles: {
          type: "array",
          items: {
            type: "object",
            properties: {
              personId: { type: "number" },
              applyDate: { type: "string" },
              jobRoleId: { type: "number" },
              jobRoleName: { type: "string" },
              jobRoleDisplay: { type: "string" },
              level: { type: "string" },
              tahunPengalaman: { type: "number" },
              levelRekomendasi: { type: "number" },
              prefered: { type: "boolean" },
              nrNote: { type: "string" },
              updatedAt: { type: "string" },
              updater: { type: "string" },
            },
          },
        },
        tools: {
          type: "array",
          items: {
            type: "object",
            properties: {
              personId: { type: "number" },
              applyDate: { type: "string" },
              softwareToolId: { type: "number" },
              softwareToolName: { type: "string" },
              softwareToolDisplay: { type: "string" },
              intensitas: { type: "number" },
              currentIntensivelyUsed: { type: "boolean" },
            },
          },
        },
        pendingRequiredActions: { type: "null" },
      },
    },
  },
};

const filterSchema = {
  type: "object",
  properties: {
    status: { type: "number" },
    message: { type: "string" },
    data: {
      type: "object",
      properties: {
        recordCount: { type: "number" },
        pageNumber: { type: "number" },
        pagesAvailable: { type: "number" },
        pageSize: { type: "number" },
        firstIndex: { type: "number" },
        lastIndex: { type: "number" },
        items: {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: { type: "number" },
              nama: { type: "string" },
              email: { type: "string" },
              nomorHP: { type: "string" },
              blackListed: { type: "boolean" },
              tanggalLamaran: { type: "string" },
              kodePelamar: { type: "string" },
              jobRoles: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    personId: { type: "number" },
                    applyDate: { type: "string" },
                    jobRoleId: { type: "number" },
                    jobRoleName: { type: "string" },
                    jobRoleDisplay: { type: "string" },
                    level: { type: "string" },
                    tahunPengalaman: { type: "number" },
                    levelRekomendasi: { type: "number" },
                    prefered: { type: "boolean" },
                    nrNote: { type: "string" },
                    updatedAt: { type: "string" },
                    updater: { type: "string" },
                  },
                },
              },
              status: { type: "string" },
              notAvailable: { type: "boolean" },
              statusCV: { type: "string" },
              invitedBy: { type: "string" },
            },
          },
        },
      },
    },
  },
};

export { pelamarAwalSchema, filterSchema };
